test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_square_root (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_square_root
    'Failed to calculate square roots'
AssertionError: Lists differ: [<built-in function pow>, <built-in functi[2453 chars]pow>] != [0.0, 1.0, 1.4142135623730951, 1.732050807[1699 chars]0662]

First differing element 0:
<built-in function pow>
0.0

Diff is 4846 characters long. Set self.maxDiff to None to see it. : Failed to calculate square roots

----------------------------------------------------------------------
Ran 2 tests in 0.051s

FAILED (failures=1)
